chore: switch CI workflow to use pnpm for dependency management and build steps

diff --git a/.github/workflows/integrate.yml b/.github/workflows/integrate.yml
--- a/.github/workflows/integrate.yml
+++ b/.github/workflows/integrate.yml
@@ -26,22 +26,22 @@ jobs:
         uses: actions/setup-node@v4
         with:
           node-version: '20.x'
-          cache: 'npm'
+          cache: 'pnpm'
 
       - name: Install Dependencies
-        run: npm install
+        run: pnpm install
 
       - name: Build Artifacts
-        run: npm build
+        run: pnpm build
 
       # - name: Run Tests
-      #   run: npm test
+      #   run: pnpm test
 
       - name: Lint Code
-        run: npm run lint || echo "Linting failed, but continuing"
+        run: pnpm lint || echo "Linting failed, but continuing"
 
       - name: Format Code
-        run: npm run format
+        run: pnpm format
 
       - name: Create Release Pull Request
         uses: changesets/action@v1
